export { LoginComponent } from "./auth/login/login.component";
export { RegisterComponent } from "./auth/register/register.component";
export { ClientHomeComponent } from "./client/home/client-home.component";
//export { SolicitacaoManutencaoComponent } from "./client/manutencao/solicitacao.component"
export { FuncionarioComponent } from "./admin/pagina-funcionario/funcionario";
export { ListarCategoriaComponent } from "./admin/listar-categoria/listar-categoria.component";
export { InserirCategoriaComponent } from  './admin/inserir-categoria/inserir-categoria.component';
export { ListarFuncionarioComponent } from './admin/listar-funcionario/listar-funcionario.component';
export { InserirFuncionarioComponent } from './admin/inserir-funcionario/inserir-funcionario.component';
export { EditarFuncionarioComponent } from './admin/editar-funcionario/editar-funcionario.component';
export { NewOrderComponent } from "./client/new-order/new-order.component"
export { ListarSolicitacoesComponent } from './admin/listar-solicitacoes/listar-solicitacoes.component';
export { EfetuarOrcamentoComponent } from './admin/efetuar-orcamento/efetuar-orcamento.component';
export { FinalizarSolicitacaoComponent } from './admin/finalizar-solicitacao/finalizar-solicitacao.component'
export { RedirecionarManutencaoComponent } from './admin/redirecionar-manutencao/redirecionar-manutencao.component'
